### PR TITLE
Add boxednode to create binaries

### PR DESCRIPTION
**Pull request by asamuzaK**

### CODE REVIEW

**Comment by asamuzaK** [comment]
@mb720 
Hi, I'm going to switch from js2bin to boxednode to create binaries.
Can you try v6.x pre-release binary and tell me if it works or not?
[Releases · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases)

Thanks

**Comment by mb720** [comment]
Sure!
I'm using the new `index` now but I can see the red box with the exclamation mark on withExEditor's icon. What do you think is the best way to debug this?

**Comment by asamuzaK** [comment]
* Check the permissions of the binary.
  Does it have an executable bit?
  If not, change permission to 755.
* Move to the directory where you saved the binary.
   ```
   cd path/to/binary
   index -h
   ```
  Is help displayed?

**Comment by mb720** [comment]
Right, I forgot to set the executable bit 🤦
Thanks for pointing that out.
The new withExEditorHost seems to work great. I'm writing this using Neovim ❤️

**Comment by asamuzaK** [comment]
It should be 755 by default.
I will create another try build later and get in touch with you again.
Thank you.

**Comment by asamuzaK** [comment]
@mb720 
New try build is ready, v6.0.0-a.11
Please check if the permission of the unzipped binary is 755 by default

Thanks

**Comment by asamuzaK** [comment]
Ah, please wait.
zipped package is only 7KB
I'll re-run the build.

**Comment by asamuzaK** [comment]
@mb720
Re-built with success.
Please check if the permission of the unzipped binary is 755 by default.

Thanks

**Comment by mb720** [comment]
>Please check if the permission of the unzipped binary is 755 by default.

No, `index` is 644.
I unzipped with `bsdtar -xf` and `unzip`.

**Comment by asamuzaK** [comment]
[build log](https://github.com/asamuzaK/withExEditorHost/runs/1534341629?check_suite_focus=true#step:8:19)
why 0600 when zipped?

**Comment by asamuzaK** [comment]
Found [Artifact zip uses chmod 0600, which some file managers dislike · Issue #37 · actions/upload-artifact](https://github.com/actions/upload-artifact/issues/37)

**Comment by asamuzaK** [comment]
@mb720
New try build.
GitHub actions seems to have an issue with zipping files (or, maybe its by design).
Anyway, assets for linux and macos are now tar.gz, not zip.
Please check if the permission of the binary is 755 by default.

Thanks

**Comment by mb720** [comment]
Yes, `index` is 755.
I also tested whether the new version works for writing with Neovim: All good! 👍

**Comment by asamuzaK** [comment]
Thanks!

**Review by mon2000x111-sketch — APPROVED** [review]

**Pull request merged**
